name: Build
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: [macos-latest]
    env:
      XC_VERSION: ${{ '12.4' }}
      XC_PROJ: ${{ 'LibraryTemplate.xcodeproj' }}
      XC_SCHEME: ${{ 'LibraryTemplate' }}
      DEMO_XC_PROJ: ${{ 'LibraryTemplateDemo.xcodeproj' }}
      DEMO_XC_SCHEME: ${{ 'LibraryTemplateDemo' }}
    steps:
    - uses: actions/checkout@v2
    - name: Select latest Xcode
      run: sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app
    - name: Build package
      run: swift build -v
    - name: Test package
      run: swift test -v
    - name: Lint podspec
      run: pod lib lint --quick
    - name: Build Demo project
      working-directory: ./Demo
      run: xcodebuild -project $DEMO_XC_PROJ -scheme $DEMO_XC_SCHEME -destination 'platform=iOS Simulator,name=iPhone 12' 
